default:
  image:
    name: hashicorp/terraform
    entrypoint: [""]

before_script:
  - rm -rf .terraform
  - terraform --version
  - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan --out plan
  artifacts:
    paths:
      - plan

apply:
  stage: apply
  environment:
    name: production
  script:
    - terraform apply --auto-approve plan
    - terraform state list
  when: manual
  allow_failure: false
  artifacts:
    paths:
      - terraform.tfstate

destroy:
    stage: destroy
    environment:
      name: production
    script:
      - terraform destroy --auto-approve
    when: manual
    only:
      - main
